src/Web/BCKFreightTMS.Web/Controllers/DashboardController.cs
namespace BCKFreightTMS.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;

    using BCKFreightTMS.Common.Enums;
    using BCKFreightTMS.Data.Common.Repositories;
    using BCKFreightTMS.Data.Models;
    using BCKFreightTMS.Services.Mapping;
    using BCKFreightTMS.Web.ViewModels;
    using BCKFreightTMS.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = "User")]
    public class DashboardController : BaseController
    {
        private readonly IDeletableEntityRepository<OrderAction> orderActions;
        private readonly UserManager<ApplicationUser> userManager;

        public DashboardController(
            IDeletableEntityRepository<OrderAction> orderActions,
            UserManager<ApplicationUser> userManager)
        {
            this.orderActions = orderActions;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var model = this.orderActions.AllAsNoTracking()
                                        .Where(a => a.OrderTo.Order.Status.Name == OrderStatusNames.InProgress.ToString() &&
                                                    a.OrderTo.Order.Creator.Id == this.userManager.GetUserId(this.User) &&
                                                    !a.OrderTo.IsFinished)
                                        .OrderBy(a => a.Until)
                                        .To<ActionIndexViewModel>()
                                        .ToList();

            return this.View(model);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }

        [Route("/Error/{StatusCode}")]
        public IActionResult StatusCodeError(int statusCode)
        {
            switch (statusCode)
            {
                case 404:
                    this.ViewBag.ErrorMessasge = $"Page not found.";
                    break;
                case 500:
                    this.ViewBag.ErrorMessasge = $"Oops! Something went wrong.";
                    break;
                default:
                    this.ViewBag.ErrorMessasge = $"Error";
                    break;
            }

            return this.View(statusCode);
        }
    }
}

src/Web/BCKFreightTMS.Web/Controllers/InvoicesController.cs
namespace BCKFreightTMS.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using AspNetCoreHero.ToastNotification.Abstractions;
    using BCKFreightTMS.Common;
    using BCKFreightTMS.Common.Enums;
    using BCKFreightTMS.Data.Common.Repositories;
    using BCKFreightTMS.Data.Models;
    using BCKFreightTMS.Services.Data;
    using BCKFreightTMS.Web.ViewModels.Invoices;
    using BCKFreightTMS.Web.ViewModels.Orders;
    using BCKFreightTMS.Web.ViewModels.Shared;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Localization;

    [Authorize(Roles = "User")]
    public class InvoicesController : Controller
    {
        private readonly IDeletableEntityRepository<InvoiceIn> invoiceIns;
        private readonly IDeletableEntityRepository<InvoiceOut> invoiceOuts;
        private readonly IOrdersService ordersService;
        private readonly INotyfService notyfService;
        private readonly IInvoicesService invoicesService;
        private readonly IStringLocalizer<OrdersController> localizer;

        public InvoicesController(
            IDeletableEntityRepository<InvoiceIn> invoiceIns,
            IDeletableEntityRepository<InvoiceOut> invoiceOuts,
            IOrdersService ordersService,
            INotyfService notyfService,
            IInvoicesService invoicesService,
            IStringLocalizer<OrdersController> localizer)
        {
            this.invoiceIns = invoiceIns;
            this.invoiceOuts = invoiceOuts;
            this.ordersService = ordersService;
            this.notyfService = notyfService;
            this.invoicesService = invoicesService;
            this.localizer = localizer;
        }

        public IActionResult Filed()
        {
            var invoices = this.invoicesService.LoadInvoiceInList(i => i.Status.Name != InvoiceStatusNames.AwaitingApproval.ToString());

            return this.View(invoices);
        }

        public IActionResult Incomplete()
        {
            var invoices = this.invoicesService.LoadInvoiceInList(i => i.Status.Name == InvoiceStatusNames.AwaitingApproval.ToString());

            return this.View(invoices);
        }

        public IActionResult ForInvoicing()
        {
            var orders = this.ordersService.GetAllOrderTos<ListOrderToViewModel>(o => o.IsFinished &&
                                                                                      o.InvoiceInId != null &&
                                                                                      o.InvoiceOutId == null)
                                           .ToList();
            return this.View(orders);
        }

        public IActionResult Correct(string id)
        {
            var model = this.invoicesService.LoadInvoiceEditModel(id);

            return this.View(model);
        }

        public IActionResult EditIn(string id)
        {
            var model = this.invoicesService.LoadInvoiceEditModel(id);

            return this.View(model);
        }

        public IActionResult EditOut(string id)
        {
            var model = this.invoicesService.LoadInvoiceOutEditModel(id);

            return this.View(model);
        }

        public IActionResult Addition(string id)
        {
            var model = this.invoicesService.LoadInvoiceOutEditModel(id);

            return this.View(model);
        }

        public IActionResult Invoicing(string id)
        {
            var model = this.invoicesService.LoadInvoiceOutModel(id);

            return this.View(model);
        }

        public IActionResult GetOrderTo(string id)
        {
            var viewModel = this.invoicesService.GetOrderTosInvoicing(id);

            return this.View(viewModel);
        }

        public IActionResult Unfinished()
        {
            var invoices = this.invoicesService.LoadInvoiceOutList(i => i.Status.Name == InvoiceStatusNames.AwaitingApproval.ToString());

            return this.View(invoices);
        }

        public IActionResult AwaitingPayment()
        {
            var invoices = this.invoicesService.LoadInvoiceOutList(i => i.Status.Name != InvoiceStatusNames.AwaitingApproval.ToString());

            return this.View(invoices);
        }

        public async Task<IActionResult> GenerateInvoice(string id)
        {
            var invHtml = await this.invoicesService.GenerateInvoiceHtml(id);
            var invModel = new InvoicePreview { Html = invHtml, InvoiceId = id };
            return this.View(invModel);
        }

        public async Task<IActionResult> DownloadInvoice(string id)
        {
            var pdfData = await this.invoicesService.GenerateInvoicePdf(id);
            return this.File(pdfData, GlobalConstants.PdfMimeType, $"Invoice.pdf");
        }

        [HttpPost]
        public async Task<IActionResult> SaveIn(InvoiceInEditModel input)
        {
            await this.invoicesService.SaveInvoiceIn(input);

            return this.RedirectToAction("Incomplete");
        }

        [HttpPost]
        public async Task<IActionResult> Finish(InvoiceInEditModel input)
        {
            var invoiceId = await this.invoicesService.SaveInvoiceIn(input);
            if (this.ordersService.ValidateFinishModel(input.OrderTos))
            {
                await this.invoicesService.UpdateInvoiceInStatusAsync(invoiceId, InvoiceStatusNames.AwaitingPayment.ToString());
                this.notyfService.Success(this.localizer["Invoice filed."]);
            }
            else
            {
                this.notyfService.Error(this.localizer["Error"]);
                return this.RedirectToAction("Incomplete");
            }

            return this.RedirectToAction("Filed");
        }

        [HttpPost]
        public async Task<IActionResult> SaveForAddition(InvoiceOutInputModel input)
        {
            var invoiceId = await this.invoicesService.CreateInvoiceOut(input);
            await this.invoicesService.UpdateInvoiceOutStatusAsync(invoiceId, InvoiceStatusNames.AwaitingApproval.ToString());
            this.notyfService.Success(this.localizer["Invoice filed."]);

            return this.RedirectToAction("ForInvoicing");
        }

        [HttpPost]
        public async Task<IActionResult> FinishOut(InvoiceOutInputModel input)
        {
            var invoiceId = await this.invoicesService.CreateInvoiceOut(input);
            await this.invoicesService.UpdateInvoiceOutStatusAsync(invoiceId, InvoiceStatusNames.AwaitingPayment.ToString());
            this.notyfService.Success(this.localizer["Invoice filed."]);

            return this.Redirect(@$"/Invoices/GenerateInvoice/{invoiceId}");
        }

        [HttpPost]
        public async Task<IActionResult> FinishAddition(InvoiceOutEditModel input)
        {
            var invoiceId = await this.invoicesService.SaveInvoiceOut(input);
            await this.invoicesService.UpdateInvoiceOutStatusAsync(invoiceId, InvoiceStatusNames.AwaitingPayment.ToString());
            this.notyfService.Success(this.localizer["Invoice filed."]);

            return this.Redirect(@$"/Invoices/GenerateInvoice/{invoiceId}");
        }

        [HttpPost]
        public async Task<IActionResult> SaveOut(InvoiceOutEditModel input)
        {
            await this.invoicesService.SaveInvoiceOut(input);

            return this.RedirectToAction("Unfinished");
        }

        public IActionResult InvoiceNoteOut(string id)
        {
            var model = this.invoicesService.LoadInvoiceNoteOutModel(id);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> InvoiceNoteOut(InvoiceNoteOutInputModel input)
        {
            try
            {
                var noteInvoiceId = await this.invoicesService.CreateInvoiceNoteOut(input);
                await this.invoicesService.UpdateInvoiceOutStatusAsync(noteInvoiceId, InvoiceStatusNames.AwaitingApproval.ToString());
            }
            catch (Exception ex)
            {
                this.notyfService.Error(ex.Message);
                return this.View(this.invoicesService.LoadInvoiceNoteOutModel(input.InvoiceOut.Id));
            }

            return this.RedirectToAction("AwaitingPayment");
        }
    }
}

src/Web/BCKFreightTMS.Web/Views/Shared/AdminLTE/_Footer.cshtml
@using BCKFreightTMS.Common

<footer class="main-footer small-box-footer position-absolute bottom-0" style=" left:0; right:0; width:auto">
    Copyright &copy; @DateTime.UtcNow.Year <strong>@GlobalConstants.SystemName</strong>. All rights reserved.
    <a asp-area="" asp-controller="Dashboard" asp-action="Privacy">Privacy</a>
</footer>

src/Web/BCKFreightTMS.Web/Views/Shared/AdminLTE/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <title>BCKFreightTMS</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <partial name="AdminLTE/_Styles" />
    </head>
    <body class="hold-transition sidebar-mini m-0">
        <partial name="_BusyIndicatorPartial" />
        <div class="wrapper">

            <partial name="AdminLTE/_TopNavigation" />

            <partial name="AdminLTE/_MainNavigation" />

            <div class="content-wrapper">
                @*<div class="content-header">
                        <div class="container-fluid">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h1 class="m-0 text-dark">Starter Page</h1>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-sm-right">
                                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                                        <li class="breadcrumb-item active">Starter Page</li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>*@
                <div class="content">
                    <div id="layout_content" class="container-fluid">
                        <partial name="_CookieConsentPartial" />
                        @RenderBody()
                    </div>
                </div>
                <a id="back-to-top" href="#" class="btn btn-primary back-to-top" style="display: none" role="button" aria-label="Scroll to top">
                    <i class="fas fa-chevron-up"></i>
                </a>
            </div>

            <partial name="AdminLTE/_Modal">

                <aside class="control-sidebar control-sidebar-dark">
                    <div class="p-3">
                        <h5>Title</h5>
                        <p>Sidebar content</p>
                    </div>
                </aside>
        </div>
    </body>
    <partial name="AdminLTE/_Scripts" />
    @await Component.InvokeAsync("Notyf")
    @await this.RenderSectionAsync("Scripts", required: false)
</html>

src/Web/BCKFreightTMS.Web/Views/Shared/AdminLTE/_Modal.cshtml
<div class="modal fade" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" style=" max-height: calc(100vh - 210px); overflow-y: auto;">

            </div>
        </div>
    </div>
</div>

src/Web/BCKFreightTMS.Web/Views/Shared/AdminLTE/_Scripts.cshtml
<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
<script src="~/plugins/bootstrap/js/bootstrap.bundle.js" asp-append-version="true"></script>
<script src="~/js/adminlte_3.1.0.js" asp-append-version="true"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

src/Web/BCKFreightTMS.Web/Views/Shared/AdminLTE/_Styles.cshtml
<link rel="stylesheet" href="~/plugins/fontawesome-free-5.15.1-web/css/all.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/adminlte_3.1.0.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" asp-append-version="true">

@*<link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="~/plugins/jqvmap/jquery.vmap.min.js">
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">*@

src/Web/BCKFreightTMS.Web/Views/Shared/AdminLTE/_TopNavigation.cshtml
@using BCKFreightTMS.Common.Enums
@using BCKFreightTMS.Data.Models
@using Microsoft.AspNetCore.Identity
@using BCKFreightTMS.Services.Data
@using BCKFreightTMS.Data.Common.Repositories
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IContactsService contacts
@inject IDeletableEntityRepository<InvoiceIn> invoices
@{
    var awaitingInvoices = this.User.IsInRole("SuperUser") ?
                         this.invoices.AllAsNoTracking()
                                    .Where(i => i.Status.Name == InvoiceStatusNames.AwaitingApproval.ToString() &&
                                                i.OrderTos.Any(o => !string.IsNullOrWhiteSpace(o.Documentation.RecievedDocumentation.Problem)))
                                    .Count() : 0;
}

<nav id="top_nav" class="main-header navbar navbar-expand navbar-white navbar-light position-fixed" style="top:0; z-index: 1">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" data-enable-remember="true" data-no-transition-after-reload="false" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            if (this.User.IsInRole(RoleNames.Admin.ToString()))
            {
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link text-dark" asp-area="Administration" asp-controller="Dashboard" asp-action="Index">@localizer["Admin"]</a>
                </li>
            }
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/">@localizer["Logout"]</a>
            </li>
        }
        else
        {
            <li class="nav-item d-none d-sm-inline-block">
                <a asp-area="Identity" asp-page="/Account/Login" class="nav-link">Login</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a asp-area="Identity" asp-page="/Account/Register" class="nav-link">Register</a>
            </li>
        }
    </ul>

    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
    @*<div class="d-block offset-4"></div>*@
    <ul class="navbar-nav ml-auto">
        @*<li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <div class="media">
                            <img src="~/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>*@
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                @if (awaitingInvoices > 0)
                {<span class="badge badge-danger navbar-badge">@awaitingInvoices</span>}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                @*<span class="dropdown-header">15 Notifications</span>*@
                <div class="dropdown-divider"></div>
                @if (awaitingInvoices > 0)
                {
                    <a asp-controller="Invoices" asp-action="Incomplete" class="dropdown-item">
                        You have @awaitingInvoices invoices for approval.
                    </a>
                }
                @*<div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>*@
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">@(awaitingInvoices > 0 ? "See All Notifications" : "No notifications")</a>
            </div>
        </li>
        <li class="nav-item">
            <partial name="_CulturePartial" />
        </li>
        @*<li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                    <i class="fas fa-th-large"></i>
                </a>
            </li>*@
    </ul>
</nav>